In [160]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge,Lasso
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.datasets import fetch_california_housing

In [161]:
data = fetch_california_housing()

In [162]:
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [163]:
# Create DataFrame
df = pd.DataFrame(data.data, columns = data.feature_names)
df['Target'] = data.target
# Split features and target
X = df.drop('Target', axis = 1)
Y = df['Target']

In [164]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422


In [165]:
df.shape

(20640, 9)

In [ ]:
# train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)

# Using Standard Scaler

In [167]:
# Feature Scaling by Standard Scaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [168]:
ridge = Ridge(alpha = 1.0)
lasso = Lasso(alpha = 0.1)
lr = LinearRegression()

In [169]:
ridge.fit(X_train_sc,Y_train)

Ridge()

In [170]:
lasso.fit(X_train_sc,Y_train)

Lasso(alpha=0.1)

In [171]:
lr.fit(X_train_sc,Y_train)

LinearRegression()

In [172]:
ridge_pred = ridge.predict(X_test_sc)

In [173]:
lasso_pred = lasso.predict(X_test_sc)

In [174]:
lr_pred = lr.predict(X_test_sc)

In [175]:
ridge_pred

array([1.43005806, 2.33449834, 1.7464598 , ..., 0.47039687, 2.87515281,
       0.75947206])

In [176]:
lasso_pred

array([1.55949685, 2.19201957, 1.62894718, ..., 1.18483091, 2.4920222 ,
       1.27109548])

In [177]:
lr_pred

array([1.42990818, 2.33445234, 1.74646549, ..., 0.46987616, 2.87541556,
       0.75920043])

In [178]:
print("Ridge R²:", r2_score(Y_test, ridge_pred))
print("Ridge MSE:", mean_squared_error(Y_test, ridge_pred))

Ridge R²: 0.5950881327591895
Ridge MSE: 0.5325640464547633


In [179]:
print("Lasso R²:", r2_score(Y_test, lasso_pred))
print("Lasso MSE:", mean_squared_error(Y_test, lasso_pred))

Lasso R²: 0.4881191475467834
Lasso MSE: 0.6732559851674377


In [180]:
print("LR R²:", r2_score(Y_test, lr_pred))
print("LR MSE:", mean_squared_error(Y_test, lr_pred))

LR R²: 0.5950798933780447
LR MSE: 0.5325748833763696


# Using Polynomial

In [211]:
# Feature Scaling by Polynomial Scaler
poly = PolynomialFeatures(degree = 2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

In [212]:
lr = LinearRegression()

In [213]:
lr.fit(X_train_poly,Y_train)

LinearRegression()

In [214]:
lr_pred2 = lr.predict(X_test_poly)

In [215]:
lr_pred2

array([1.21224456, 2.75704221, 1.63854537, ..., 0.37006188, 3.44337814,
       0.83296067])

In [216]:
print("LR R²:", r2_score(Y_test, lr_pred2))
print("LR MSE:", mean_squared_error(Y_test, lr_pred2))

LR R²: 0.6450974066957569
LR MSE: 0.46678889032162946
